######################################################################
# Automatically generated by qmake (3.0) ?? 3? 28 10:40:11 2014
######################################################################
QT+=core gui widgets opengl
TEMPLATE = app
TARGET = opengl
INCLUDEPATH += .

# Input
HEADERS+=glwidget.h
SOURCES += main.cpp glwidget.cpp
